{
    "name": "Shopify Bridge Sync",
    "version": "1.1.0",
    "category": "Connector",
    "summary": "Shopify to Odoo Bridge Connector",
    "description": "Sync products, orders, customers between Shopify and Odoo",
    "author": "Your Company",
    "website": "https://yourcompany.com",
    "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/sync_store_views.xml",
        "views/sync_catalog_views.xml",
        "views/sync_sale_views.xml",
        "views/sync_contact_views.xml",
        "views/sync_journal_views.xml",
        "views/sync_dashboard_views.xml",
        "views/sync_wizard_views.xml",
        "views/sync_menus.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
